//! Autogenerated weights for trust_registry
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-02-16, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/dock-node
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet=trust_registry
// --extra
// --repeat=20
// --extrinsic=*
// --steps=50
// --template=node/module-weight-template.hbs
// --output=./pallets/core/src/modules/trust_registry/weights.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for trust_registry.
pub trait WeightInfo {
    fn init_or_update_trust_registry_sr25519(n: u32, g: u32) -> Weight;
    fn init_or_update_trust_registry_ed25519(n: u32, g: u32) -> Weight;
    fn init_or_update_trust_registry_secp256k1(n: u32, g: u32) -> Weight;
    fn set_schemas_metadata_sr25519(i: u32, v: u32, s: u32) -> Weight;
    fn set_schemas_metadata_ed25519(i: u32, v: u32, s: u32) -> Weight;
    fn set_schemas_metadata_secp256k1(i: u32, v: u32, s: u32) -> Weight;
    fn update_delegated_issuers_sr25519(i: u32) -> Weight;
    fn update_delegated_issuers_ed25519(i: u32) -> Weight;
    fn update_delegated_issuers_secp256k1(i: u32) -> Weight;
    fn suspend_issuers_sr25519(i: u32) -> Weight;
    fn suspend_issuers_ed25519(i: u32) -> Weight;
    fn suspend_issuers_secp256k1(i: u32) -> Weight;
    fn unsuspend_issuers_sr25519(i: u32) -> Weight;
    fn unsuspend_issuers_ed25519(i: u32) -> Weight;
    fn unsuspend_issuers_secp256k1(i: u32) -> Weight;
}

/// Weights for trust_registry using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn init_or_update_trust_registry_sr25519(_n: u32, _g: u32) -> Weight {
        Weight::from_ref_time(68_011_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    fn init_or_update_trust_registry_ed25519(n: u32, _g: u32) -> Weight {
        Weight::from_ref_time(66_136_000) // Standard Error: 10_000
            .saturating_add(Weight::from_ref_time(20_000).saturating_mul(n as u64))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    fn init_or_update_trust_registry_secp256k1(n: u32, g: u32) -> Weight {
        Weight::from_ref_time(157_320_000) // Standard Error: 20_000
            .saturating_add(Weight::from_ref_time(119_000).saturating_mul(n as u64)) // Standard Error: 6_000
            .saturating_add(Weight::from_ref_time(13_000).saturating_mul(g as u64))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    fn set_schemas_metadata_sr25519(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(578_763_000) // Standard Error: 211_000
            .saturating_add(Weight::from_ref_time(5_232_000).saturating_mul(v as u64)) // Standard Error: 1_109_000
            .saturating_add(Weight::from_ref_time(351_123_000).saturating_mul(s as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(v as u64)))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(s as u64)))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(v as u64)))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(s as u64)))
    }
    fn set_schemas_metadata_ed25519(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(564_042_000) // Standard Error: 236_000
            .saturating_add(Weight::from_ref_time(7_077_000).saturating_mul(v as u64)) // Standard Error: 1_238_000
            .saturating_add(Weight::from_ref_time(320_208_000).saturating_mul(s as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(v as u64)))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(s as u64)))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(v as u64)))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(s as u64)))
    }
    fn set_schemas_metadata_secp256k1(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(171_418_000) // Standard Error: 281_000
            .saturating_add(Weight::from_ref_time(9_369_000).saturating_mul(v as u64)) // Standard Error: 1_474_000
            .saturating_add(Weight::from_ref_time(360_965_000).saturating_mul(s as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(v as u64)))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(s as u64)))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(v as u64)))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(s as u64)))
    }
    fn update_delegated_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(64_341_000) // Standard Error: 22_000
            .saturating_add(Weight::from_ref_time(216_000).saturating_mul(i as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn update_delegated_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(63_354_000) // Standard Error: 12_000
            .saturating_add(Weight::from_ref_time(67_000).saturating_mul(i as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn update_delegated_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(152_925_000) // Standard Error: 23_000
            .saturating_add(Weight::from_ref_time(372_000).saturating_mul(i as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn suspend_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(61_769_000) // Standard Error: 40_000
            .saturating_add(Weight::from_ref_time(6_281_000).saturating_mul(i as u64))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn suspend_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(66_098_000) // Standard Error: 13_000
            .saturating_add(Weight::from_ref_time(5_848_000).saturating_mul(i as u64))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn suspend_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(156_245_000) // Standard Error: 10_000
            .saturating_add(Weight::from_ref_time(5_930_000).saturating_mul(i as u64))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(65_711_000) // Standard Error: 10_000
            .saturating_add(Weight::from_ref_time(7_394_000).saturating_mul(i as u64))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(60_848_000) // Standard Error: 36_000
            .saturating_add(Weight::from_ref_time(7_613_000).saturating_mul(i as u64))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(170_754_000) // Standard Error: 43_000
            .saturating_add(Weight::from_ref_time(7_070_000).saturating_mul(i as u64))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn init_or_update_trust_registry_sr25519(_n: u32, _g: u32) -> Weight {
        Weight::from_ref_time(68_011_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn init_or_update_trust_registry_ed25519(n: u32, _g: u32) -> Weight {
        Weight::from_ref_time(66_136_000) // Standard Error: 10_000
            .saturating_add(Weight::from_ref_time(20_000).saturating_mul(n as u64))
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn init_or_update_trust_registry_secp256k1(n: u32, g: u32) -> Weight {
        Weight::from_ref_time(157_320_000) // Standard Error: 20_000
            .saturating_add(Weight::from_ref_time(119_000).saturating_mul(n as u64)) // Standard Error: 6_000
            .saturating_add(Weight::from_ref_time(13_000).saturating_mul(g as u64))
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn set_schemas_metadata_sr25519(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(578_763_000) // Standard Error: 211_000
            .saturating_add(Weight::from_ref_time(5_232_000).saturating_mul(v as u64)) // Standard Error: 1_109_000
            .saturating_add(Weight::from_ref_time(351_123_000).saturating_mul(s as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(s as u64)))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(s as u64)))
    }
    fn set_schemas_metadata_ed25519(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(564_042_000) // Standard Error: 236_000
            .saturating_add(Weight::from_ref_time(7_077_000).saturating_mul(v as u64)) // Standard Error: 1_238_000
            .saturating_add(Weight::from_ref_time(320_208_000).saturating_mul(s as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(s as u64)))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(s as u64)))
    }
    fn set_schemas_metadata_secp256k1(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(171_418_000) // Standard Error: 281_000
            .saturating_add(Weight::from_ref_time(9_369_000).saturating_mul(v as u64)) // Standard Error: 1_474_000
            .saturating_add(Weight::from_ref_time(360_965_000).saturating_mul(s as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(s as u64)))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(s as u64)))
    }
    fn update_delegated_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(64_341_000) // Standard Error: 22_000
            .saturating_add(Weight::from_ref_time(216_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn update_delegated_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(63_354_000) // Standard Error: 12_000
            .saturating_add(Weight::from_ref_time(67_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn update_delegated_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(152_925_000) // Standard Error: 23_000
            .saturating_add(Weight::from_ref_time(372_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn suspend_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(61_769_000) // Standard Error: 40_000
            .saturating_add(Weight::from_ref_time(6_281_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn suspend_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(66_098_000) // Standard Error: 13_000
            .saturating_add(Weight::from_ref_time(5_848_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn suspend_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(156_245_000) // Standard Error: 10_000
            .saturating_add(Weight::from_ref_time(5_930_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(65_711_000) // Standard Error: 10_000
            .saturating_add(Weight::from_ref_time(7_394_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(60_848_000) // Standard Error: 36_000
            .saturating_add(Weight::from_ref_time(7_613_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(170_754_000) // Standard Error: 43_000
            .saturating_add(Weight::from_ref_time(7_070_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads(1_u64.saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes(1_u64.saturating_mul(i as u64)))
    }
}
