//! Autogenerated weights for trust_registry
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-03-11, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/dock-node
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet=trust_registry
// --extra
// --repeat=20
// --extrinsic=*
// --steps=50
// --template=node/module-weight-template-without-system.hbs
// --output=./pallets/core/src/modules/trust_registry/weights.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, RuntimeDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for trust_registry.
pub trait WeightInfo {
    fn init_or_update_trust_registry_sr25519(n: u32, g: u32) -> Weight;
    fn init_or_update_trust_registry_ed25519(n: u32, g: u32) -> Weight;
    fn init_or_update_trust_registry_secp256k1(n: u32, g: u32) -> Weight;
    fn set_schemas_metadata_sr25519(i: u32, v: u32, s: u32) -> Weight;
    fn set_schemas_metadata_ed25519(i: u32, v: u32, s: u32) -> Weight;
    fn set_schemas_metadata_secp256k1(i: u32, v: u32, s: u32) -> Weight;
    fn update_delegated_issuers_sr25519(i: u32) -> Weight;
    fn update_delegated_issuers_ed25519(i: u32) -> Weight;
    fn update_delegated_issuers_secp256k1(i: u32) -> Weight;
    fn suspend_issuers_sr25519(i: u32) -> Weight;
    fn suspend_issuers_ed25519(i: u32) -> Weight;
    fn suspend_issuers_secp256k1(i: u32) -> Weight;
    fn unsuspend_issuers_sr25519(i: u32) -> Weight;
    fn unsuspend_issuers_ed25519(i: u32) -> Weight;
    fn unsuspend_issuers_secp256k1(i: u32) -> Weight;
}

/// Weights for trust_registry using the Substrate node and recommended hardware.
pub struct SubstrateWeight<W>(PhantomData<W>);
impl<W: Get<RuntimeDbWeight>> WeightInfo for SubstrateWeight<W> {
    fn init_or_update_trust_registry_sr25519(_n: u32, _g: u32) -> Weight {
        Weight::from_ref_time(60_159_000)
            .saturating_add(W::get().reads(5))
            .saturating_add(W::get().writes(4))
    }
    fn init_or_update_trust_registry_ed25519(n: u32, g: u32) -> Weight {
        Weight::from_ref_time(57_097_000) // Standard Error: 6_000
            .saturating_add(Weight::from_ref_time(50_000).saturating_mul(n as u64)) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(6_000).saturating_mul(g as u64))
            .saturating_add(W::get().reads(5))
            .saturating_add(W::get().writes(4))
    }
    fn init_or_update_trust_registry_secp256k1(n: u32, g: u32) -> Weight {
        Weight::from_ref_time(146_444_000) // Standard Error: 14_000
            .saturating_add(Weight::from_ref_time(139_000).saturating_mul(n as u64)) // Standard Error: 4_000
            .saturating_add(Weight::from_ref_time(26_000).saturating_mul(g as u64))
            .saturating_add(W::get().reads(5))
            .saturating_add(W::get().writes(4))
    }
    fn set_schemas_metadata_sr25519(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(0) // Standard Error: 140_000
            .saturating_add(Weight::from_ref_time(5_575_000).saturating_mul(i as u64)) // Standard Error: 140_000
            .saturating_add(Weight::from_ref_time(7_136_000).saturating_mul(v as u64)) // Standard Error: 735_000
            .saturating_add(Weight::from_ref_time(278_953_000).saturating_mul(s as u64))
            .saturating_add(W::get().reads(3))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(v as u64)))
            .saturating_add(W::get().reads((1 as u64).saturating_mul(s as u64)))
            .saturating_add(W::get().writes(1))
            .saturating_add(W::get().writes((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes((2 as u64).saturating_mul(v as u64)))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(s as u64)))
    }
    fn set_schemas_metadata_ed25519(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(50_379_000) // Standard Error: 113_000
            .saturating_add(Weight::from_ref_time(455_000).saturating_mul(i as u64)) // Standard Error: 113_000
            .saturating_add(Weight::from_ref_time(6_782_000).saturating_mul(v as u64)) // Standard Error: 597_000
            .saturating_add(Weight::from_ref_time(252_016_000).saturating_mul(s as u64))
            .saturating_add(W::get().reads(3))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(v as u64)))
            .saturating_add(W::get().reads((1 as u64).saturating_mul(s as u64)))
            .saturating_add(W::get().writes(1))
            .saturating_add(W::get().writes((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes((2 as u64).saturating_mul(v as u64)))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(s as u64)))
    }
    fn set_schemas_metadata_secp256k1(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(0) // Standard Error: 128_000
            .saturating_add(Weight::from_ref_time(5_650_000).saturating_mul(i as u64)) // Standard Error: 128_000
            .saturating_add(Weight::from_ref_time(7_839_000).saturating_mul(v as u64)) // Standard Error: 672_000
            .saturating_add(Weight::from_ref_time(268_238_000).saturating_mul(s as u64))
            .saturating_add(W::get().reads(3))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(v as u64)))
            .saturating_add(W::get().reads((1 as u64).saturating_mul(s as u64)))
            .saturating_add(W::get().writes(1))
            .saturating_add(W::get().writes((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes((2 as u64).saturating_mul(v as u64)))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(s as u64)))
    }
    fn update_delegated_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(59_046_000) // Standard Error: 15_000
            .saturating_add(Weight::from_ref_time(2_343_000).saturating_mul(i as u64))
            .saturating_add(W::get().reads(4))
            .saturating_add(W::get().reads((1 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes(2))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn update_delegated_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(62_602_000) // Standard Error: 25_000
            .saturating_add(Weight::from_ref_time(1_719_000).saturating_mul(i as u64))
            .saturating_add(W::get().reads(4))
            .saturating_add(W::get().reads((1 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes(2))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn update_delegated_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(152_670_000) // Standard Error: 45_000
            .saturating_add(Weight::from_ref_time(2_504_000).saturating_mul(i as u64))
            .saturating_add(W::get().reads(4))
            .saturating_add(W::get().reads((1 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes(2))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn suspend_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(59_922_000) // Standard Error: 11_000
            .saturating_add(Weight::from_ref_time(4_919_000).saturating_mul(i as u64))
            .saturating_add(W::get().reads(3))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes(1))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn suspend_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(58_670_000) // Standard Error: 16_000
            .saturating_add(Weight::from_ref_time(4_886_000).saturating_mul(i as u64))
            .saturating_add(W::get().reads(3))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes(1))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn suspend_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(153_174_000) // Standard Error: 22_000
            .saturating_add(Weight::from_ref_time(4_823_000).saturating_mul(i as u64))
            .saturating_add(W::get().reads(3))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes(1))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(57_694_000) // Standard Error: 46_000
            .saturating_add(Weight::from_ref_time(6_469_000).saturating_mul(i as u64))
            .saturating_add(W::get().reads(3))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes(1))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(52_800_000) // Standard Error: 23_000
            .saturating_add(Weight::from_ref_time(6_371_000).saturating_mul(i as u64))
            .saturating_add(W::get().reads(3))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes(1))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(145_569_000) // Standard Error: 32_000
            .saturating_add(Weight::from_ref_time(6_415_000).saturating_mul(i as u64))
            .saturating_add(W::get().reads(3))
            .saturating_add(W::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(W::get().writes(1))
            .saturating_add(W::get().writes((1 as u64).saturating_mul(i as u64)))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn init_or_update_trust_registry_sr25519(_n: u32, _g: u32) -> Weight {
        Weight::from_ref_time(60_159_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn init_or_update_trust_registry_ed25519(n: u32, g: u32) -> Weight {
        Weight::from_ref_time(57_097_000) // Standard Error: 6_000
            .saturating_add(Weight::from_ref_time(50_000).saturating_mul(n as u64)) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(6_000).saturating_mul(g as u64))
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn init_or_update_trust_registry_secp256k1(n: u32, g: u32) -> Weight {
        Weight::from_ref_time(146_444_000) // Standard Error: 14_000
            .saturating_add(Weight::from_ref_time(139_000).saturating_mul(n as u64)) // Standard Error: 4_000
            .saturating_add(Weight::from_ref_time(26_000).saturating_mul(g as u64))
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn set_schemas_metadata_sr25519(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(0) // Standard Error: 140_000
            .saturating_add(Weight::from_ref_time(5_575_000).saturating_mul(i as u64)) // Standard Error: 140_000
            .saturating_add(Weight::from_ref_time(7_136_000).saturating_mul(v as u64)) // Standard Error: 735_000
            .saturating_add(Weight::from_ref_time(278_953_000).saturating_mul(s as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(s as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes((2 as u64).saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(s as u64)))
    }
    fn set_schemas_metadata_ed25519(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(50_379_000) // Standard Error: 113_000
            .saturating_add(Weight::from_ref_time(455_000).saturating_mul(i as u64)) // Standard Error: 113_000
            .saturating_add(Weight::from_ref_time(6_782_000).saturating_mul(v as u64)) // Standard Error: 597_000
            .saturating_add(Weight::from_ref_time(252_016_000).saturating_mul(s as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(s as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes((2 as u64).saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(s as u64)))
    }
    fn set_schemas_metadata_secp256k1(i: u32, v: u32, s: u32) -> Weight {
        Weight::from_ref_time(0) // Standard Error: 128_000
            .saturating_add(Weight::from_ref_time(5_650_000).saturating_mul(i as u64)) // Standard Error: 128_000
            .saturating_add(Weight::from_ref_time(7_839_000).saturating_mul(v as u64)) // Standard Error: 672_000
            .saturating_add(Weight::from_ref_time(268_238_000).saturating_mul(s as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(s as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes((2 as u64).saturating_mul(v as u64)))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(s as u64)))
    }
    fn update_delegated_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(59_046_000) // Standard Error: 15_000
            .saturating_add(Weight::from_ref_time(2_343_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn update_delegated_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(62_602_000) // Standard Error: 25_000
            .saturating_add(Weight::from_ref_time(1_719_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn update_delegated_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(152_670_000) // Standard Error: 45_000
            .saturating_add(Weight::from_ref_time(2_504_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn suspend_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(59_922_000) // Standard Error: 11_000
            .saturating_add(Weight::from_ref_time(4_919_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn suspend_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(58_670_000) // Standard Error: 16_000
            .saturating_add(Weight::from_ref_time(4_886_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn suspend_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(153_174_000) // Standard Error: 22_000
            .saturating_add(Weight::from_ref_time(4_823_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_sr25519(i: u32) -> Weight {
        Weight::from_ref_time(57_694_000) // Standard Error: 46_000
            .saturating_add(Weight::from_ref_time(6_469_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_ed25519(i: u32) -> Weight {
        Weight::from_ref_time(52_800_000) // Standard Error: 23_000
            .saturating_add(Weight::from_ref_time(6_371_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
    }
    fn unsuspend_issuers_secp256k1(i: u32) -> Weight {
        Weight::from_ref_time(145_569_000) // Standard Error: 32_000
            .saturating_add(Weight::from_ref_time(6_415_000).saturating_mul(i as u64))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((2 as u64).saturating_mul(i as u64)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(i as u64)))
    }
}
