//! Autogenerated weights for did
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2022-07-06, STEPS: `[50, ]`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("mainnet"), DB CACHE: 128

// Executed Command:
// ./target/release/dock-node
// benchmark
// --execution
// wasm
// --chain
// mainnet
// --wasm-execution
// compiled
// --pallet
// did
// --extra
// --extrinsic
// *
// --repeat
// 20
// --steps
// 50
// --output
// ./pallets/core_mods/src/modules/did/weights.rs
// --template
// node/module-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for did.
pub trait WeightInfo {
	fn add_keys_sr25519(k: u32, ) -> Weight;
	fn add_keys_ed25519(k: u32, ) -> Weight;
	fn add_keys_secp256k1(k: u32, ) -> Weight;
	fn remove_keys_sr25519(k: u32, ) -> Weight;
	fn remove_keys_ed25519(k: u32, ) -> Weight;
	fn remove_keys_secp256k1(k: u32, ) -> Weight;
	fn add_controllers_sr25519(k: u32, ) -> Weight;
	fn add_controllers_ed25519(k: u32, ) -> Weight;
	fn add_controllers_secp256k1(k: u32, ) -> Weight;
	fn remove_controllers_sr25519(k: u32, ) -> Weight;
	fn remove_controllers_ed25519(k: u32, ) -> Weight;
	fn remove_controllers_secp256k1(k: u32, ) -> Weight;
	fn add_service_endpoint_sr25519(o: u32, l: u32, i: u32, ) -> Weight;
	fn add_service_endpoint_ed25519(o: u32, l: u32, i: u32, ) -> Weight;
	fn add_service_endpoint_secp256k1(o: u32, l: u32, i: u32, ) -> Weight;
	fn remove_service_endpoint_sr25519(i: u32, ) -> Weight;
	fn remove_service_endpoint_ed25519(i: u32, ) -> Weight;
	fn remove_service_endpoint_secp256k1(i: u32, ) -> Weight;
	fn remove_onchain_did_sr25519() -> Weight;
	fn remove_onchain_did_ed25519() -> Weight;
	fn remove_onchain_did_secp256k1() -> Weight;
	fn new_onchain(k: u32, c: u32, ) -> Weight;
	fn new_offchain(k: u32, ) -> Weight;
	fn set_offchain_did_doc_ref(k: u32, ) -> Weight;
	fn remove_offchain_did() -> Weight;
}

/// Weights for did using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn add_keys_sr25519(k: u32, ) -> Weight {
		(76_227_000 as Weight)
			// Standard Error: 161_000
			.saturating_add((2_602_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_keys_ed25519(k: u32, ) -> Weight {
		(80_173_000 as Weight)
			// Standard Error: 214_000
			.saturating_add((1_407_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_keys_secp256k1(k: u32, ) -> Weight {
		(219_880_000 as Weight)
			// Standard Error: 101_000
			.saturating_add((2_955_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_keys_sr25519(k: u32, ) -> Weight {
		(79_980_000 as Weight)
			// Standard Error: 86_000
			.saturating_add((6_435_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_keys_ed25519(k: u32, ) -> Weight {
		(76_440_000 as Weight)
			// Standard Error: 50_000
			.saturating_add((6_818_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_keys_secp256k1(k: u32, ) -> Weight {
		(227_900_000 as Weight)
			// Standard Error: 63_000
			.saturating_add((6_724_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_controllers_sr25519(k: u32, ) -> Weight {
		(73_993_000 as Weight)
			// Standard Error: 25_000
			.saturating_add((7_156_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_controllers_ed25519(k: u32, ) -> Weight {
		(71_793_000 as Weight)
			// Standard Error: 32_000
			.saturating_add((7_081_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_controllers_secp256k1(k: u32, ) -> Weight {
		(222_240_000 as Weight)
			// Standard Error: 53_000
			.saturating_add((7_042_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_controllers_sr25519(k: u32, ) -> Weight {
		(77_527_000 as Weight)
			// Standard Error: 70_000
			.saturating_add((7_332_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_controllers_ed25519(k: u32, ) -> Weight {
		(74_707_000 as Weight)
			// Standard Error: 94_000
			.saturating_add((7_344_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_controllers_secp256k1(k: u32, ) -> Weight {
		(225_787_000 as Weight)
			// Standard Error: 242_000
			.saturating_add((7_566_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_service_endpoint_sr25519(o: u32, _l: u32, _i: u32, ) -> Weight {
		(81_869_000 as Weight)
			// Standard Error: 31_000
			.saturating_add((243_000 as Weight).saturating_mul(o as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn add_service_endpoint_ed25519(o: u32, l: u32, i: u32, ) -> Weight {
		(73_675_000 as Weight)
			// Standard Error: 56_000
			.saturating_add((404_000 as Weight).saturating_mul(o as Weight))
			// Standard Error: 56_000
			.saturating_add((199_000 as Weight).saturating_mul(l as Weight))
			// Standard Error: 2_000
			.saturating_add((20_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn add_service_endpoint_secp256k1(o: u32, l: u32, i: u32, ) -> Weight {
		(215_620_000 as Weight)
			// Standard Error: 101_000
			.saturating_add((710_000 as Weight).saturating_mul(o as Weight))
			// Standard Error: 101_000
			.saturating_add((707_000 as Weight).saturating_mul(l as Weight))
			// Standard Error: 4_000
			.saturating_add((10_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn remove_service_endpoint_sr25519(i: u32, ) -> Weight {
		(82_113_000 as Weight)
			// Standard Error: 1_000
			.saturating_add((10_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn remove_service_endpoint_ed25519(i: u32, ) -> Weight {
		(79_844_000 as Weight)
			// Standard Error: 1_000
			.saturating_add((6_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn remove_service_endpoint_secp256k1(i: u32, ) -> Weight {
		(228_685_000 as Weight)
			// Standard Error: 7_000
			.saturating_add((50_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn remove_onchain_did_sr25519() -> Weight {
		(103_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(24 as Weight))
	}
	fn remove_onchain_did_ed25519() -> Weight {
		(101_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(24 as Weight))
	}
	fn remove_onchain_did_secp256k1() -> Weight {
		(254_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(24 as Weight))
	}
	fn new_onchain(k: u32, c: u32, ) -> Weight {
		(29_027_000 as Weight)
			// Standard Error: 44_000
			.saturating_add((2_079_000 as Weight).saturating_mul(k as Weight))
			// Standard Error: 44_000
			.saturating_add((2_095_000 as Weight).saturating_mul(c as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(c as Weight)))
	}
	fn new_offchain(k: u32, ) -> Weight {
		(21_775_000 as Weight)
			// Standard Error: 0
			.saturating_add((6_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	fn set_offchain_did_doc_ref(k: u32, ) -> Weight {
		(22_930_000 as Weight)
			// Standard Error: 0
			.saturating_add((6_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	fn remove_offchain_did() -> Weight {
		(22_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn add_keys_sr25519(k: u32, ) -> Weight {
		(76_227_000 as Weight)
			// Standard Error: 161_000
			.saturating_add((2_602_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_keys_ed25519(k: u32, ) -> Weight {
		(80_173_000 as Weight)
			// Standard Error: 214_000
			.saturating_add((1_407_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_keys_secp256k1(k: u32, ) -> Weight {
		(219_880_000 as Weight)
			// Standard Error: 101_000
			.saturating_add((2_955_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_keys_sr25519(k: u32, ) -> Weight {
		(79_980_000 as Weight)
			// Standard Error: 86_000
			.saturating_add((6_435_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_keys_ed25519(k: u32, ) -> Weight {
		(76_440_000 as Weight)
			// Standard Error: 50_000
			.saturating_add((6_818_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_keys_secp256k1(k: u32, ) -> Weight {
		(227_900_000 as Weight)
			// Standard Error: 63_000
			.saturating_add((6_724_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_controllers_sr25519(k: u32, ) -> Weight {
		(73_993_000 as Weight)
			// Standard Error: 25_000
			.saturating_add((7_156_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_controllers_ed25519(k: u32, ) -> Weight {
		(71_793_000 as Weight)
			// Standard Error: 32_000
			.saturating_add((7_081_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_controllers_secp256k1(k: u32, ) -> Weight {
		(222_240_000 as Weight)
			// Standard Error: 53_000
			.saturating_add((7_042_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_controllers_sr25519(k: u32, ) -> Weight {
		(77_527_000 as Weight)
			// Standard Error: 70_000
			.saturating_add((7_332_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_controllers_ed25519(k: u32, ) -> Weight {
		(74_707_000 as Weight)
			// Standard Error: 94_000
			.saturating_add((7_344_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn remove_controllers_secp256k1(k: u32, ) -> Weight {
		(225_787_000 as Weight)
			// Standard Error: 242_000
			.saturating_add((7_566_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
	}
	fn add_service_endpoint_sr25519(o: u32, _l: u32, _i: u32, ) -> Weight {
		(81_869_000 as Weight)
			// Standard Error: 31_000
			.saturating_add((243_000 as Weight).saturating_mul(o as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn add_service_endpoint_ed25519(o: u32, l: u32, i: u32, ) -> Weight {
		(73_675_000 as Weight)
			// Standard Error: 56_000
			.saturating_add((404_000 as Weight).saturating_mul(o as Weight))
			// Standard Error: 56_000
			.saturating_add((199_000 as Weight).saturating_mul(l as Weight))
			// Standard Error: 2_000
			.saturating_add((20_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn add_service_endpoint_secp256k1(o: u32, l: u32, i: u32, ) -> Weight {
		(215_620_000 as Weight)
			// Standard Error: 101_000
			.saturating_add((710_000 as Weight).saturating_mul(o as Weight))
			// Standard Error: 101_000
			.saturating_add((707_000 as Weight).saturating_mul(l as Weight))
			// Standard Error: 4_000
			.saturating_add((10_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn remove_service_endpoint_sr25519(i: u32, ) -> Weight {
		(82_113_000 as Weight)
			// Standard Error: 1_000
			.saturating_add((10_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn remove_service_endpoint_ed25519(i: u32, ) -> Weight {
		(79_844_000 as Weight)
			// Standard Error: 1_000
			.saturating_add((6_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn remove_service_endpoint_secp256k1(i: u32, ) -> Weight {
		(228_685_000 as Weight)
			// Standard Error: 7_000
			.saturating_add((50_000 as Weight).saturating_mul(i as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn remove_onchain_did_sr25519() -> Weight {
		(103_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(24 as Weight))
	}
	fn remove_onchain_did_ed25519() -> Weight {
		(101_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(24 as Weight))
	}
	fn remove_onchain_did_secp256k1() -> Weight {
		(254_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(24 as Weight))
	}
	fn new_onchain(k: u32, c: u32, ) -> Weight {
		(29_027_000 as Weight)
			// Standard Error: 44_000
			.saturating_add((2_079_000 as Weight).saturating_mul(k as Weight))
			// Standard Error: 44_000
			.saturating_add((2_095_000 as Weight).saturating_mul(c as Weight))
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(c as Weight)))
	}
	fn new_offchain(k: u32, ) -> Weight {
		(21_775_000 as Weight)
			// Standard Error: 0
			.saturating_add((6_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	fn set_offchain_did_doc_ref(k: u32, ) -> Weight {
		(22_930_000 as Weight)
			// Standard Error: 0
			.saturating_add((6_000 as Weight).saturating_mul(k as Weight))
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	fn remove_offchain_did() -> Weight {
		(22_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
}
