//! Autogenerated weights for did
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2022-08-01, STEPS: `[50, ]`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Native), WASM-EXECUTION: Interpreted, CHAIN: Some("mainnet"), DB CACHE: 128

// Executed Command:
// ./target/production/dock-node
// benchmark
// --execution=native
// --chain=mainnet
// --pallet=did
// --extra
// --extrinsic=*
// --repeat=20
// --steps=50
// --template=node/module-weight-template.hbs
// --output=./pallets/core_mods/src/modules/did/weights.rs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for did.
pub trait WeightInfo {
    fn add_keys_sr25519(k: u32) -> Weight;
    fn add_keys_ed25519(k: u32) -> Weight;
    fn add_keys_secp256k1(k: u32) -> Weight;
    fn remove_keys_sr25519(k: u32) -> Weight;
    fn remove_keys_ed25519(k: u32) -> Weight;
    fn remove_keys_secp256k1(k: u32) -> Weight;
    fn add_controllers_sr25519(k: u32) -> Weight;
    fn add_controllers_ed25519(k: u32) -> Weight;
    fn add_controllers_secp256k1(k: u32) -> Weight;
    fn remove_controllers_sr25519(k: u32) -> Weight;
    fn remove_controllers_ed25519(k: u32) -> Weight;
    fn remove_controllers_secp256k1(k: u32) -> Weight;
    fn add_service_endpoint_sr25519(o: u32, l: u32, i: u32) -> Weight;
    fn add_service_endpoint_ed25519(o: u32, l: u32, i: u32) -> Weight;
    fn add_service_endpoint_secp256k1(o: u32, l: u32, i: u32) -> Weight;
    fn remove_service_endpoint_sr25519(i: u32) -> Weight;
    fn remove_service_endpoint_ed25519(i: u32) -> Weight;
    fn remove_service_endpoint_secp256k1(i: u32) -> Weight;
    fn remove_onchain_did_sr25519() -> Weight;
    fn remove_onchain_did_ed25519() -> Weight;
    fn remove_onchain_did_secp256k1() -> Weight;
    fn new_onchain(k: u32, c: u32) -> Weight;
    fn new_offchain(k: u32) -> Weight;
    fn set_offchain_did_doc_ref(k: u32) -> Weight;
    fn remove_offchain_did() -> Weight;
}

/// Weights for did using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn add_keys_sr25519(k: u32) -> Weight {
        (56_930_000 as Weight)
            // Standard Error: 34_000
            .saturating_add((1_072_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_keys_ed25519(k: u32) -> Weight {
        (57_701_000 as Weight)
            // Standard Error: 29_000
            .saturating_add((712_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_keys_secp256k1(k: u32) -> Weight {
        (162_329_000 as Weight)
            // Standard Error: 575_000
            .saturating_add((1_296_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_sr25519(k: u32) -> Weight {
        (62_781_000 as Weight)
            // Standard Error: 26_000
            .saturating_add((2_804_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_ed25519(k: u32) -> Weight {
        (60_847_000 as Weight)
            // Standard Error: 30_000
            .saturating_add((2_717_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_secp256k1(k: u32) -> Weight {
        (165_718_000 as Weight)
            // Standard Error: 72_000
            .saturating_add((2_734_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_sr25519(k: u32) -> Weight {
        (60_892_000 as Weight)
            // Standard Error: 34_000
            .saturating_add((3_351_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_ed25519(k: u32) -> Weight {
        (60_140_000 as Weight)
            // Standard Error: 59_000
            .saturating_add((3_061_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_secp256k1(k: u32) -> Weight {
        (168_684_000 as Weight)
            // Standard Error: 69_000
            .saturating_add((2_770_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_sr25519(k: u32) -> Weight {
        (60_478_000 as Weight)
            // Standard Error: 119_000
            .saturating_add((3_625_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_ed25519(k: u32) -> Weight {
        (60_970_000 as Weight)
            // Standard Error: 43_000
            .saturating_add((3_273_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_secp256k1(k: u32) -> Weight {
        (165_267_000 as Weight)
            // Standard Error: 57_000
            .saturating_add((3_198_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_service_endpoint_sr25519(o: u32, l: u32, i: u32) -> Weight {
        (62_630_000 as Weight)
            // Standard Error: 15_000
            .saturating_add((146_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 15_000
            .saturating_add((82_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 0
            .saturating_add((3_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn add_service_endpoint_ed25519(o: u32, l: u32, i: u32) -> Weight {
        (61_631_000 as Weight)
            // Standard Error: 16_000
            .saturating_add((60_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 16_000
            .saturating_add((58_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 0
            .saturating_add((4_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn add_service_endpoint_secp256k1(o: u32, l: u32, i: u32) -> Weight {
        (152_391_000 as Weight)
            // Standard Error: 236_000
            .saturating_add((719_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 236_000
            .saturating_add((810_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 11_000
            .saturating_add((80_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_sr25519(i: u32) -> Weight {
        (62_886_000 as Weight)
            // Standard Error: 1_000
            .saturating_add((28_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_ed25519(i: u32) -> Weight {
        (62_262_000 as Weight)
            // Standard Error: 0
            .saturating_add((9_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_secp256k1(i: u32) -> Weight {
        (166_356_000 as Weight)
            // Standard Error: 1_000
            .saturating_add((12_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn remove_onchain_did_sr25519() -> Weight {
        (85_904_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(34 as Weight))
    }
    fn remove_onchain_did_ed25519() -> Weight {
        (86_475_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(34 as Weight))
    }
    fn remove_onchain_did_secp256k1() -> Weight {
        (193_139_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(34 as Weight))
    }
    fn new_onchain(k: u32, c: u32) -> Weight {
        (10_672_000 as Weight)
            // Standard Error: 4_000
            .saturating_add((549_000 as Weight).saturating_mul(k as Weight))
            // Standard Error: 4_000
            .saturating_add((606_000 as Weight).saturating_mul(c as Weight))
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(c as Weight)))
    }
    fn new_offchain(k: u32) -> Weight {
        (9_652_000 as Weight)
            // Standard Error: 0
            .saturating_add((2_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn set_offchain_did_doc_ref(k: u32) -> Weight {
        (10_356_000 as Weight)
            // Standard Error: 0
            .saturating_add((1_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn remove_offchain_did() -> Weight {
        (10_057_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn add_keys_sr25519(k: u32) -> Weight {
        (56_930_000 as Weight)
            // Standard Error: 34_000
            .saturating_add((1_072_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_keys_ed25519(k: u32) -> Weight {
        (57_701_000 as Weight)
            // Standard Error: 29_000
            .saturating_add((712_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_keys_secp256k1(k: u32) -> Weight {
        (162_329_000 as Weight)
            // Standard Error: 575_000
            .saturating_add((1_296_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_sr25519(k: u32) -> Weight {
        (62_781_000 as Weight)
            // Standard Error: 26_000
            .saturating_add((2_804_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_ed25519(k: u32) -> Weight {
        (60_847_000 as Weight)
            // Standard Error: 30_000
            .saturating_add((2_717_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_secp256k1(k: u32) -> Weight {
        (165_718_000 as Weight)
            // Standard Error: 72_000
            .saturating_add((2_734_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_sr25519(k: u32) -> Weight {
        (60_892_000 as Weight)
            // Standard Error: 34_000
            .saturating_add((3_351_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_ed25519(k: u32) -> Weight {
        (60_140_000 as Weight)
            // Standard Error: 59_000
            .saturating_add((3_061_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_secp256k1(k: u32) -> Weight {
        (168_684_000 as Weight)
            // Standard Error: 69_000
            .saturating_add((2_770_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_sr25519(k: u32) -> Weight {
        (60_478_000 as Weight)
            // Standard Error: 119_000
            .saturating_add((3_625_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_ed25519(k: u32) -> Weight {
        (60_970_000 as Weight)
            // Standard Error: 43_000
            .saturating_add((3_273_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_secp256k1(k: u32) -> Weight {
        (165_267_000 as Weight)
            // Standard Error: 57_000
            .saturating_add((3_198_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_service_endpoint_sr25519(o: u32, l: u32, i: u32) -> Weight {
        (62_630_000 as Weight)
            // Standard Error: 15_000
            .saturating_add((146_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 15_000
            .saturating_add((82_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 0
            .saturating_add((3_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn add_service_endpoint_ed25519(o: u32, l: u32, i: u32) -> Weight {
        (61_631_000 as Weight)
            // Standard Error: 16_000
            .saturating_add((60_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 16_000
            .saturating_add((58_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 0
            .saturating_add((4_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn add_service_endpoint_secp256k1(o: u32, l: u32, i: u32) -> Weight {
        (152_391_000 as Weight)
            // Standard Error: 236_000
            .saturating_add((719_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 236_000
            .saturating_add((810_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 11_000
            .saturating_add((80_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_sr25519(i: u32) -> Weight {
        (62_886_000 as Weight)
            // Standard Error: 1_000
            .saturating_add((28_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_ed25519(i: u32) -> Weight {
        (62_262_000 as Weight)
            // Standard Error: 0
            .saturating_add((9_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_secp256k1(i: u32) -> Weight {
        (166_356_000 as Weight)
            // Standard Error: 1_000
            .saturating_add((12_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn remove_onchain_did_sr25519() -> Weight {
        (85_904_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(34 as Weight))
    }
    fn remove_onchain_did_ed25519() -> Weight {
        (86_475_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(34 as Weight))
    }
    fn remove_onchain_did_secp256k1() -> Weight {
        (193_139_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(34 as Weight))
    }
    fn new_onchain(k: u32, c: u32) -> Weight {
        (10_672_000 as Weight)
            // Standard Error: 4_000
            .saturating_add((549_000 as Weight).saturating_mul(k as Weight))
            // Standard Error: 4_000
            .saturating_add((606_000 as Weight).saturating_mul(c as Weight))
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(c as Weight)))
    }
    fn new_offchain(k: u32) -> Weight {
        (9_652_000 as Weight)
            // Standard Error: 0
            .saturating_add((2_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn set_offchain_did_doc_ref(k: u32) -> Weight {
        (10_356_000 as Weight)
            // Standard Error: 0
            .saturating_add((1_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn remove_offchain_did() -> Weight {
        (10_057_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
}
