//! Autogenerated weights for did
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2022-07-07, STEPS: `[50, ]`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("mainnet"), DB CACHE: 128

// Executed Command:
// ./target/release/dock-node
// benchmark
// --execution
// wasm
// --chain
// mainnet
// --wasm-execution
// compiled
// --pallet
// did
// --extra
// --extrinsic
// *
// --repeat
// 20
// --steps
// 50
// --output
// ./pallets/core_mods/src/modules/did/weights.rs
// --template
// node/module-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for did.
pub trait WeightInfo {
    fn add_keys_sr25519(k: u32) -> Weight;
    fn add_keys_ed25519(k: u32) -> Weight;
    fn add_keys_secp256k1(k: u32) -> Weight;
    fn remove_keys_sr25519(k: u32) -> Weight;
    fn remove_keys_ed25519(k: u32) -> Weight;
    fn remove_keys_secp256k1(k: u32) -> Weight;
    fn add_controllers_sr25519(k: u32) -> Weight;
    fn add_controllers_ed25519(k: u32) -> Weight;
    fn add_controllers_secp256k1(k: u32) -> Weight;
    fn remove_controllers_sr25519(k: u32) -> Weight;
    fn remove_controllers_ed25519(k: u32) -> Weight;
    fn remove_controllers_secp256k1(k: u32) -> Weight;
    fn add_service_endpoint_sr25519(o: u32, l: u32, i: u32) -> Weight;
    fn add_service_endpoint_ed25519(o: u32, l: u32, i: u32) -> Weight;
    fn add_service_endpoint_secp256k1(o: u32, l: u32, i: u32) -> Weight;
    fn remove_service_endpoint_sr25519(i: u32) -> Weight;
    fn remove_service_endpoint_ed25519(i: u32) -> Weight;
    fn remove_service_endpoint_secp256k1(i: u32) -> Weight;
    fn remove_onchain_did_sr25519() -> Weight;
    fn remove_onchain_did_ed25519() -> Weight;
    fn remove_onchain_did_secp256k1() -> Weight;
    fn new_onchain(k: u32, c: u32) -> Weight;
    fn new_offchain(k: u32) -> Weight;
    fn set_offchain_did_doc_ref(k: u32) -> Weight;
    fn remove_offchain_did() -> Weight;
}

/// Weights for did using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn add_keys_sr25519(k: u32) -> Weight {
        (101_870_000 as Weight)
            // Standard Error: 165_000
            .saturating_add((5_828_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_keys_ed25519(k: u32) -> Weight {
        (98_491_000 as Weight)
            // Standard Error: 147_000
            .saturating_add((5_686_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_keys_secp256k1(k: u32) -> Weight {
        (395_836_000 as Weight)
            // Standard Error: 136_000
            .saturating_add((4_934_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_sr25519(k: u32) -> Weight {
        (110_480_000 as Weight)
            // Standard Error: 309_000
            .saturating_add((10_174_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_ed25519(k: u32) -> Weight {
        (108_908_000 as Weight)
            // Standard Error: 361_000
            .saturating_add((9_923_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_secp256k1(k: u32) -> Weight {
        (402_140_000 as Weight)
            // Standard Error: 217_000
            .saturating_add((9_749_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_sr25519(k: u32) -> Weight {
        (102_747_000 as Weight)
            // Standard Error: 22_000
            .saturating_add((9_465_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_ed25519(k: u32) -> Weight {
        (99_354_000 as Weight)
            // Standard Error: 24_000
            .saturating_add((9_410_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_secp256k1(k: u32) -> Weight {
        (388_532_000 as Weight)
            // Standard Error: 135_000
            .saturating_add((10_218_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_sr25519(k: u32) -> Weight {
        (107_529_000 as Weight)
            // Standard Error: 26_000
            .saturating_add((9_884_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_ed25519(k: u32) -> Weight {
        (104_314_000 as Weight)
            // Standard Error: 30_000
            .saturating_add((9_857_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_secp256k1(k: u32) -> Weight {
        (398_055_000 as Weight)
            // Standard Error: 130_000
            .saturating_add((10_342_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_service_endpoint_sr25519(o: u32, l: u32, i: u32) -> Weight {
        (109_894_000 as Weight)
            // Standard Error: 12_000
            .saturating_add((444_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 12_000
            .saturating_add((119_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 0
            .saturating_add((9_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn add_service_endpoint_ed25519(o: u32, l: u32, i: u32) -> Weight {
        (107_255_000 as Weight)
            // Standard Error: 11_000
            .saturating_add((379_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 11_000
            .saturating_add((92_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 0
            .saturating_add((9_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn add_service_endpoint_secp256k1(o: u32, l: u32, i: u32) -> Weight {
        (398_755_000 as Weight)
            // Standard Error: 81_000
            .saturating_add((192_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 81_000
            .saturating_add((202_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 4_000
            .saturating_add((19_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_sr25519(i: u32) -> Weight {
        (113_932_000 as Weight)
            // Standard Error: 0
            .saturating_add((19_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_ed25519(i: u32) -> Weight {
        (110_529_000 as Weight)
            // Standard Error: 0
            .saturating_add((16_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_secp256k1(i: u32) -> Weight {
        (401_500_000 as Weight)
            // Standard Error: 4_000
            .saturating_add((29_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(T::DbWeight::get().reads(5 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
    fn remove_onchain_did_sr25519() -> Weight {
        (138_586_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(24 as Weight))
    }
    fn remove_onchain_did_ed25519() -> Weight {
        (133_881_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(24 as Weight))
    }
    fn remove_onchain_did_secp256k1() -> Weight {
        (437_394_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(24 as Weight))
    }
    fn new_onchain(k: u32, c: u32) -> Weight {
        (28_212_000 as Weight)
            // Standard Error: 62_000
            .saturating_add((5_168_000 as Weight).saturating_mul(k as Weight))
            // Standard Error: 62_000
            .saturating_add((3_737_000 as Weight).saturating_mul(c as Weight))
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(c as Weight)))
    }
    fn new_offchain(k: u32) -> Weight {
        (29_269_000 as Weight)
            // Standard Error: 0
            .saturating_add((8_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn set_offchain_did_doc_ref(k: u32) -> Weight {
        (30_844_000 as Weight)
            // Standard Error: 0
            .saturating_add((8_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn remove_offchain_did() -> Weight {
        (29_438_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn add_keys_sr25519(k: u32) -> Weight {
        (101_870_000 as Weight)
            // Standard Error: 165_000
            .saturating_add((5_828_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_keys_ed25519(k: u32) -> Weight {
        (98_491_000 as Weight)
            // Standard Error: 147_000
            .saturating_add((5_686_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_keys_secp256k1(k: u32) -> Weight {
        (395_836_000 as Weight)
            // Standard Error: 136_000
            .saturating_add((4_934_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_sr25519(k: u32) -> Weight {
        (110_480_000 as Weight)
            // Standard Error: 309_000
            .saturating_add((10_174_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_ed25519(k: u32) -> Weight {
        (108_908_000 as Weight)
            // Standard Error: 361_000
            .saturating_add((9_923_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_keys_secp256k1(k: u32) -> Weight {
        (402_140_000 as Weight)
            // Standard Error: 217_000
            .saturating_add((9_749_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_sr25519(k: u32) -> Weight {
        (102_747_000 as Weight)
            // Standard Error: 22_000
            .saturating_add((9_465_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_ed25519(k: u32) -> Weight {
        (99_354_000 as Weight)
            // Standard Error: 24_000
            .saturating_add((9_410_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_controllers_secp256k1(k: u32) -> Weight {
        (388_532_000 as Weight)
            // Standard Error: 135_000
            .saturating_add((10_218_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_sr25519(k: u32) -> Weight {
        (107_529_000 as Weight)
            // Standard Error: 26_000
            .saturating_add((9_884_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_ed25519(k: u32) -> Weight {
        (104_314_000 as Weight)
            // Standard Error: 30_000
            .saturating_add((9_857_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn remove_controllers_secp256k1(k: u32) -> Weight {
        (398_055_000 as Weight)
            // Standard Error: 130_000
            .saturating_add((10_342_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
    }
    fn add_service_endpoint_sr25519(o: u32, l: u32, i: u32) -> Weight {
        (109_894_000 as Weight)
            // Standard Error: 12_000
            .saturating_add((444_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 12_000
            .saturating_add((119_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 0
            .saturating_add((9_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn add_service_endpoint_ed25519(o: u32, l: u32, i: u32) -> Weight {
        (107_255_000 as Weight)
            // Standard Error: 11_000
            .saturating_add((379_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 11_000
            .saturating_add((92_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 0
            .saturating_add((9_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn add_service_endpoint_secp256k1(o: u32, l: u32, i: u32) -> Weight {
        (398_755_000 as Weight)
            // Standard Error: 81_000
            .saturating_add((192_000 as Weight).saturating_mul(o as Weight))
            // Standard Error: 81_000
            .saturating_add((202_000 as Weight).saturating_mul(l as Weight))
            // Standard Error: 4_000
            .saturating_add((19_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_sr25519(i: u32) -> Weight {
        (113_932_000 as Weight)
            // Standard Error: 0
            .saturating_add((19_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_ed25519(i: u32) -> Weight {
        (110_529_000 as Weight)
            // Standard Error: 0
            .saturating_add((16_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn remove_service_endpoint_secp256k1(i: u32) -> Weight {
        (401_500_000 as Weight)
            // Standard Error: 4_000
            .saturating_add((29_000 as Weight).saturating_mul(i as Weight))
            .saturating_add(RocksDbWeight::get().reads(5 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
    fn remove_onchain_did_sr25519() -> Weight {
        (138_586_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(24 as Weight))
    }
    fn remove_onchain_did_ed25519() -> Weight {
        (133_881_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(24 as Weight))
    }
    fn remove_onchain_did_secp256k1() -> Weight {
        (437_394_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(24 as Weight))
    }
    fn new_onchain(k: u32, c: u32) -> Weight {
        (28_212_000 as Weight)
            // Standard Error: 62_000
            .saturating_add((5_168_000 as Weight).saturating_mul(k as Weight))
            // Standard Error: 62_000
            .saturating_add((3_737_000 as Weight).saturating_mul(c as Weight))
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(k as Weight)))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(c as Weight)))
    }
    fn new_offchain(k: u32) -> Weight {
        (29_269_000 as Weight)
            // Standard Error: 0
            .saturating_add((8_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn set_offchain_did_doc_ref(k: u32) -> Weight {
        (30_844_000 as Weight)
            // Standard Error: 0
            .saturating_add((8_000 as Weight).saturating_mul(k as Weight))
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn remove_offchain_did() -> Weight {
        (29_438_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
}
