//! Autogenerated weights for blob
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2022-07-07, STEPS: `[50, ]`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("mainnet"), DB CACHE: 128

// Executed Command:
// ./target/release/dock-node
// benchmark
// --execution
// wasm
// --chain
// mainnet
// --wasm-execution
// compiled
// --pallet
// blob
// --extra
// --extrinsic
// *
// --repeat
// 20
// --steps
// 50
// --output
// ./pallets/core_mods/src/modules/blob/weights.rs
// --template
// node/module-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for blob.
pub trait WeightInfo {
    fn new_sr25519(s: u32) -> Weight;
    fn new_ed25519(s: u32) -> Weight;
    fn new_secp256k1(s: u32) -> Weight;
}

/// Weights for blob using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn new_sr25519(s: u32) -> Weight {
        (79_572_000 as Weight)
            // Standard Error: 0
            .saturating_add((10_000 as Weight).saturating_mul(s as Weight))
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn new_ed25519(s: u32) -> Weight {
        (75_818_000 as Weight)
            // Standard Error: 0
            .saturating_add((7_000 as Weight).saturating_mul(s as Weight))
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    fn new_secp256k1(s: u32) -> Weight {
        (362_217_000 as Weight)
            // Standard Error: 5_000
            .saturating_add((7_000 as Weight).saturating_mul(s as Weight))
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn new_sr25519(s: u32) -> Weight {
        (79_572_000 as Weight)
            // Standard Error: 0
            .saturating_add((10_000 as Weight).saturating_mul(s as Weight))
            .saturating_add(RocksDbWeight::get().reads(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn new_ed25519(s: u32) -> Weight {
        (75_818_000 as Weight)
            // Standard Error: 0
            .saturating_add((7_000 as Weight).saturating_mul(s as Weight))
            .saturating_add(RocksDbWeight::get().reads(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn new_secp256k1(s: u32) -> Weight {
        (362_217_000 as Weight)
            // Standard Error: 5_000
            .saturating_add((7_000 as Weight).saturating_mul(s as Weight))
            .saturating_add(RocksDbWeight::get().reads(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
}
