//! Autogenerated weights for revoke
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-05-11, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/dock-node
// benchmark
// pallet
// --wasm-execution=compiled
// --pallet=revoke
// --extra
// --repeat=20
// --extrinsic=*
// --steps=50
// --template=node/module-weight-template.hbs
// --output=./tmp

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for revoke.
pub trait WeightInfo {
    fn revoke_sr25519(r: u32) -> Weight;
    fn revoke_ed25519(r: u32) -> Weight;
    fn revoke_secp256k1(r: u32) -> Weight;
    fn unrevoke_sr25519(r: u32) -> Weight;
    fn unrevoke_ed25519(r: u32) -> Weight;
    fn unrevoke_secp256k1(r: u32) -> Weight;
    fn remove_registry_sr25519() -> Weight;
    fn remove_registry_ed25519() -> Weight;
    fn remove_registry_secp256k1() -> Weight;
    fn new_registry(c: u32) -> Weight;
}

/// Weights for revoke using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn revoke_sr25519(r: u32) -> Weight {
        Weight::from_ref_time(45_358_000) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(1_093_000).saturating_mul(r as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn revoke_ed25519(r: u32) -> Weight {
        Weight::from_ref_time(48_514_000) // Standard Error: 5_000
            .saturating_add(Weight::from_ref_time(1_033_000).saturating_mul(r as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn revoke_secp256k1(r: u32) -> Weight {
        Weight::from_ref_time(137_080_000) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(1_082_000).saturating_mul(r as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn unrevoke_sr25519(r: u32) -> Weight {
        Weight::from_ref_time(50_652_000) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(1_100_000).saturating_mul(r as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn unrevoke_ed25519(r: u32) -> Weight {
        Weight::from_ref_time(45_609_000) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(1_046_000).saturating_mul(r as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn unrevoke_secp256k1(r: u32) -> Weight {
        Weight::from_ref_time(137_650_000) // Standard Error: 3_000
            .saturating_add(Weight::from_ref_time(1_092_000).saturating_mul(r as u64))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
            .saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn remove_registry_sr25519() -> Weight {
        Weight::from_ref_time(164_000_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(103))
    }
    fn remove_registry_ed25519() -> Weight {
        Weight::from_ref_time(160_000_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(103))
    }
    fn remove_registry_secp256k1() -> Weight {
        Weight::from_ref_time(258_000_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(103))
    }
    fn new_registry(c: u32) -> Weight {
        Weight::from_ref_time(12_256_000) // Standard Error: 4_000
            .saturating_add(Weight::from_ref_time(89_000).saturating_mul(c as u64))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn revoke_sr25519(r: u32) -> Weight {
        Weight::from_ref_time(45_358_000) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(1_093_000).saturating_mul(r as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn revoke_ed25519(r: u32) -> Weight {
        Weight::from_ref_time(48_514_000) // Standard Error: 5_000
            .saturating_add(Weight::from_ref_time(1_033_000).saturating_mul(r as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn revoke_secp256k1(r: u32) -> Weight {
        Weight::from_ref_time(137_080_000) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(1_082_000).saturating_mul(r as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn unrevoke_sr25519(r: u32) -> Weight {
        Weight::from_ref_time(50_652_000) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(1_100_000).saturating_mul(r as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn unrevoke_ed25519(r: u32) -> Weight {
        Weight::from_ref_time(45_609_000) // Standard Error: 2_000
            .saturating_add(Weight::from_ref_time(1_046_000).saturating_mul(r as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn unrevoke_secp256k1(r: u32) -> Weight {
        Weight::from_ref_time(137_650_000) // Standard Error: 3_000
            .saturating_add(Weight::from_ref_time(1_092_000).saturating_mul(r as u64))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(r as u64)))
    }
    fn remove_registry_sr25519() -> Weight {
        Weight::from_ref_time(164_000_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(103))
    }
    fn remove_registry_ed25519() -> Weight {
        Weight::from_ref_time(160_000_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(103))
    }
    fn remove_registry_secp256k1() -> Weight {
        Weight::from_ref_time(258_000_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(103))
    }
    fn new_registry(c: u32) -> Weight {
        Weight::from_ref_time(12_256_000) // Standard Error: 4_000
            .saturating_add(Weight::from_ref_time(89_000).saturating_mul(c as u64))
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
}
