#!/bin/bash

# This script is used to generate and set (rotate) new session keys for the validator.
# Pass flag --nocolor to disable colored output.

# The script will will exit if any command fails
set -ueo pipefail

DEFAULT_NODE_RPC_ENDPOINT='http://localhost:9933'
NOCOLOR='--nocolor'

# If the node RPC endpoint is not provided, use the default one.
# The RPC endpoint should be the first argument and should not be $NOCOLOR
if [[ $# -ge 1 && $1 != $NOCOLOR ]]
then
  node_rpc_url=$1
else
  node_rpc_url=$DEFAULT_NODE_RPC_ENDPOINT
fi

# Make the RPC call `author_rotateKeys` to the node using curl and get the response which will contain the session key.
# `-s` flag is silent mode, i.e. preventing the progress from being displayed.
rpc_resp=$(curl -s $node_rpc_url -H "Content-Type:application/json;charset=utf-8" -d '[{"jsonrpc":"2.0","id":1,"method":"author_rotateKeys","params":[]}]')

# Extract the hex formatted session key from the RPC call's response.
session_key_regex='(0x[A-Fa-f0-9]+)'
if [[ $rpc_resp =~ $session_key_regex ]]
then
  session_key=${BASH_REMATCH[1]}
else
  echo "Cannot get session key. Regex failed. Curl response below:"
  echo $rpc_resp
  exit 1
fi

# Get the last argument
last_arg=''
for last_arg; do true; done

# If the last argument is not $NOCOLOR, print colored output
if [[ $last_arg != $NOCOLOR ]]
then
  # For colored output
  GREEN_COLOR='\033[1;32m'
  NOCOLOR='\033[0m'

  echo -e "The session key is ${GREEN_COLOR}$session_key${NOCOLOR}"
else
  echo "The session key is $session_key"
fi
