#!/bin/bash

# Starts a dock test node in docker for testing. Automatically deletes the container on exit.
# Arguments passed to this script are forwarded to the node binary.
#
# Example use:
#
# ```bash
# # Start a local test node
# ./run_node_in_docker --dev
#
# # Start a testnet node
# ./run_node_in_docker --chain=poa_testnet --rpc-external --ws-external --rpc-cors=all
# ```

set -uexo pipefail

cd $(dirname $0)/..

# build the node if it has not already been built. This prints the docker build logs.
docker build . >&2

# run the node with the random name output by the build command
docker run -p 9944:9944 -p 9933:9933 -p 30333:30333 --rm $(docker build -q .) $@
