- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: Create SSH access security group
    amazon.aws.ec2_security_group:
      region: "{{ aws_region }}"
      aws_access_key_id: "{{ aws_access_key_id }}"
      aws_secret_access_key: "{{ aws_secret_key }}"
      name: SSH port open (created by ansible)
      description: Allows connecting to node directly via SSH (created by ansible)
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

  - name: Get EC2 instance state
    amazon.aws.ec2_instance:
      aws_access_key_id: "{{ aws_access_key_id }}"
      aws_secret_access_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      instance: "{{ instance_id }}"
    register: instances

  - name: EC2 instance info
    ansible.builtin.debug:
      msg: Existing security groups {{ instances['instances'][0] | json_query('security_groups[*].group_id') }}

  - name: Add SSH open port group to the EC2 instance
    amazon.aws.ec2_instance:
      aws_access_key_id: "{{ aws_access_key_id }}"
      aws_secret_access_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      instance: "{{ instance_id }}"
      security_groups: "{{ instances['instances'][0] | json_query('security_groups[*].group_id') + ['SSH port open (created by ansible)'] }}"
