- hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: Get EC2 instance state
    amazon.aws.ec2_instance:
      aws_access_key_id: "{{ aws_access_key_id }}"
      aws_secret_access_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      instance_ids: [ "{{instance_id}}" ]
    register: instances

  - name: EC2 instance info
    ansible.builtin.debug:
      msg: Existing security groups {{ instances['instances'][0] | json_query('security_groups[*].group_name') }}

  - name: Remove SSH access group from the EC2 instance
    amazon.aws.ec2_instance:
      aws_access_key_id: "{{ aws_access_key_id }}"
      aws_secret_access_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      instance_ids: [ "{{instance_id}}" ]
      security_groups: "{{ instances['instances'][0] | json_query('security_groups[*].group_name') | difference(['SSH port open (created by ansible)']) }}"
