- hosts: '{{ host }}'
  tasks:
  - name: Pull latest code
    when: rebuild_node | default('true') | bool
    shell:
      chdir: /home/ubuntu/dock-substrate
      cmd: git pull

  - name: Build node
    when: rebuild_node | default('true') | bool
    shell:
      chdir: /home/ubuntu/dock-substrate
      cmd: cargo build --release --features testnet

  - name: Stop node
    become: yes
    become_method: sudo
    service: name=dock-node state=stopped

  # purge-chain command does not remove frontier folder. Not removing entire `dock_pos_testnet` to keep the keys
  - name: Purge db
    become: yes
    become_method: sudo
    file:
      state: absent
      path: /home/ubuntu/dock-node/chains/dock_pos_testnet/db

  - name: Purge frontier
    become: yes
    become_method: sudo
    file:
      state: absent
      path: /home/ubuntu/dock-node/chains/dock_pos_testnet/frontier

  - name: Start node
    become: yes
    become_method: sudo
    service: name=dock-node state=started
