name: Docker Build

on:
  push:
    branches:
      - ci/DCKB_542_DockerHub
    tags:
      - mainnet
      - testnet
      - fastblock
      - ci-test

jobs:
 build-testnet-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: GitHub Tag Name example
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"

      - name: Build Production image
        if: ${{ github.ref_name }} == "ci-test"
        run: |
         echo "Building production image: ${{  github.ref_name }}"

      - name: Build Test image
        if: ${{ github.ref_name }} != "ci-test"
        run: |
         echo "Building test image: ${{  github.ref_name }}"

#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          build-args: features=--features=testnet
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dock-substrate:testnet
