name: Docker Container Build

on:
  push:
    branches:
      - master
      - ci/DCKB-542_startsWith_fastblock
    tags:
      - mainnet
      - testnet
      - fastblock*
      - ci_test

jobs:
 build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set tag name
        shell: bash
        run: |
          export TAG_NAME=master
          if [${{github.ref_name}} == 'mainnet'] || [${{github.ref_name}} == 'testnet'] || [${{github.ref_name}} == 'ci_test']
          then
            export TAG_NAME=${{github.ref_name}}
          fi
          echo "::set-env name=TAG_NAME::$TAG_NAME"

      - name: 'Build production ${{ github.ref_name }} image'
        if: github.ref_name == 'mainnet' || github.ref_name == 'testnet'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: features=--features=${{ env.TAG_NAME }}
          tags: docknetwork/dock-substrate:${{ env.TAG_NAME }}

      - name: Build release fastblock image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            features=--features=fastblock
            release=Y
          tags: docknetwork/dock-substrate:fastblock_${{ env.TAG_NAME }}
