name: Docker Container Build

on:
  push:
    branches:
      - master
    tags:
      - mainnet
      - testnet

jobs:
 build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set tag name
        id: image_tag
        shell: bash
        run: |
          export TAG_NAME=master
          if [[ '${{github.ref_name}}' == 'mainnet' || '${{github.ref_name}}' == 'testnet' ]];
          then
            export TAG_NAME=${{github.ref_name}}
          fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: 'Build production ${{ steps.image_tag.outputs.TAG_NAME }} image'
        if: steps.image_tag.outputs.TAG_NAME != 'master'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: features=--features=${{ steps.image_tag.outputs.TAG_NAME }},wasmtime
          tags: docknetwork/dock-substrate:${{ steps.image_tag.outputs.TAG_NAME }}

      - name: 'Build release fastblock_${{ steps.image_tag.outputs.TAG_NAME }} image'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            features=--features=fastblock,wasmtime
            release=Y
          tags: docknetwork/dock-substrate:fastblock_${{ steps.image_tag.outputs.TAG_NAME }}
