name: Docker Container Build

on:
  push:
    branches:
      - master
    tags:
      - mainnet
      - testnet
      - fastblock

jobs:
 build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 'Build production ${{ github.ref_name }} image'
        if: github.ref_name == 'mainnet' || github.ref_name == 'testnet'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: features=--features=${{ github.ref_name }},wasmtime
          tags: docknetwork/dock-substrate:${{ github.ref_name}}

      - name: Build release fastblock image
        if: github.ref_name == 'fastblock'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            features=--features=fastblock,wasmtime
            release=Y
          tags: docknetwork/dock-substrate:fastblock
