name: Docker Container Build

on:
  push:
    branches:
      - ci/DCKB_542_DockerHub
    tags:
      - mainnet
      - testnet
      - fastblock
      - ci-test

jobs:
 build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Production image
        if: github.ref_name == 'mainnet' || github.ref_name == 'testnet' || github.ref_name == 'ci-test'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: features=--features=${{ github.ref_name }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dock-substrate:${{ github.ref_name}}

      - name: Build Test image
        if: github.ref_name == 'fastblock' || github.ref_name != 'ci-test'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            features=--features=fastblock
            release=--release
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dock-substrate:${{ github.ref_name}}
