name: Increase Node Disk

on:
  workflow_dispatch:
    inputs:
      network:
        type: environment
        description: "Whether updating a testnet or mainnet node"
        required: true
      aws_region:
        description: "AWS region of EC2 instance to modify"
        required: true
      instance_id:
        description: "The EC2 instance id"
        required: true
      disk_size:
        description: "The total size of the disk desired (GB)"
        required: true


jobs:
  increase-disk:
    environment: ${{inputs.network}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Hosts Config
        id: get-hosts
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ${{vars.S3_ANSIBLE_HOST_FILE}}
          destination: ./ansible-hosts
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{vars.S3_REGION}}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          which python3
          python3 -m pip install --upgrade pip
          pip install --user boto3
          ls -l

      - name: Run playbook
        uses: arillso/action.playbook@master
        with:
          # Required, playbook filepath
          playbook: ./scripts/ansible/aws/ec2-set-volume-size.yml
          inventory: ./ansible-hosts
          galaxy_file: ./scripts/ansible/aws/requirements.yml
          verbose: 3
          extra_vars: "aws_region=${{github.event.inputs.aws_region}} aws_secret_key=${{secrets.AWS_SECRET_KEY}} aws_access_key_id=${{secrets.AWS_ACCESS_KEY_ID}} name='${{github.event.inputs.instance_name}}' volume_size=${{github.event.inputs.disk_size}} ansible_python_interpreter='/usr/bin/python3'"
