name: Increase Node Disk

on:
  workflow_dispatch:
    inputs:
      network:
        type: environment
        description: "Whether updating a testnet or mainnet node"
        required: true
      aws_region:
        description: "AWS region of EC2 instance to modify"
        required: true
      instance_id:
        description: "The EC2 instance id"
        required: true
      disk_size:
        description: "The total size of the disk desired (GB)"
        required: true


jobs:
  increase-disk:
    environment: ${{inputs.network}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Hosts Config
        id: get-hosts
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ${{vars.S3_ANSIBLE_HOST_FILE}}
          destination: ./ansible-hosts
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{vars.S3_REGION}}

      - name: Run playbook
        uses: arillso/action.playbook@master
        with:
          # Required, playbook filepath
          playbook: ./scripts/ansible/aws/ec2-set-volume-size.yml
          inventory: ./ansible-hosts
          galaxy_file: ./scripts/ansible/aws/requirements.yml
          verbose: 3
          extra_vars: "aws_region=${{github.event.inputs.aws_region}} instance_id=${{inputs.instance_id}} aws_secret_key=${{secrets.AWS_SECRET_KEY}} aws_access_key_id=${{secrets.AWS_ACCESS_KEY_ID}} volume_size=${{github.event.inputs.disk_size}} ansible_python_interpreter='/usr/bin/python3'"

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: extend-partition
        with:
          aws-region: ${{ inputs.aws_region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          instance-ids: ${{ inputs.instance_id }}

          working-directory: /home/ubuntu/application
          command: sudo growpart /dev/nvme0n1 1
          comment: Partition increased by Github Action

      # Catch SSM outputs
      - name: Get the outputs
        if: steps.extend-partition.outcome == 'success'
        run: echo "The Command id is ${{ steps.extend-partition.outputs.command-id }}"

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: extend-file-system
        if: steps.extend-partition.outcome == 'success'
        with:
          aws-region: ${{ inputs.aws_region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          instance-ids: ${{ inputs.instance_id }}

          working-directory: /home/ubuntu/application
          command: sudo resize2fs /dev/nvme0n1p1
          comment: File system increased by Github Action
