name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Ensure Standard Formatting
        run: cargo +nightly fmt -- --check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-08-23
          override: true
      - name: Install WASM
        run: rustup target add wasm32-unknown-unknown --toolchain nightly-2022-08-23
      - name: Ensure docs are buildable
        run: cargo doc --no-deps
      - name: Run tests
        run: cargo test --all

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./scripts/integration_tests
