name: Tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly-2023-03-09
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-03-09
          override: true
      - name: Install WASM
        run: rustup target add wasm32-unknown-unknown --toolchain nightly-2023-03-09
      - name: Ensure docs are buildable
        run: cargo doc --no-deps
      - name: Run tests
        run: cargo test --release --all

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly-2023-03-09
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-03-09
          override: true
      - name: Install WASM
        run: rustup target add wasm32-unknown-unknown --toolchain nightly-2023-03-09
      # Temporary solution: disk space is exceeded on the runner machine
      - run: ./scripts/integration_tests
